Repository DUNE-DAQ/dfmodules, pull requests merged in 2022-06, with the labels that each got.

#185 Updated version
  CMakeLists.txt
Labels: version change

#187 using try_receive instead of receive for TRB
  plugins/TriggerRecordBuilder.cpp
Labels: enhancement

#193 Updated version
  CMakeLists.txt
Labels: version change

#200 Remove a couple dangling references to networkmanager package
  cmake/dfmodulesConfig.cmake.in
  plugins/FakeDataProd.cpp
Labels: maintenance
