Repository DUNE-DAQ/dfmodules, pull requests merged in 2024-03, with the labels that each got.

#335 Update version
  CMakeLists.txt
Labels: version change

#334 Changes to support additional file transfer metadata
  include/dfmodules/DataStore.hpp
  plugins/DataWriter.cpp
  plugins/HDF5DataStore.hpp
  plugins/TPStreamWriter.cpp
  schema/dfmodules/hdf5datastore.jsonnet
Labels: deliverable subtask

#336 Kbiery/tpswriter improvements
  plugins/TPStreamWriter.cpp
  plugins/TPStreamWriter.hpp
  schema/dfmodules/tpstreamwriter.jsonnet
  src/TPBundleHandler.cpp
  src/dfmodules/TPBundleHandler.hpp
Labels: miscellaneous deliverable

#337 Updated integtests to use the new TTCM config params for setting the …
  CMakeLists.txt
  integtest/disabled_output_test.py
  integtest/insufficient_disk_space_test.py
  integtest/large_trigger_record_test.py
  integtest/multi_output_file_test.py
Labels: miscellaneous deliverable
